### ISSUE TITLE
Uhh... Talking girls

### ISSUE THREAD

**Issue by Iniquitatis** [ManlyMarco/KK_PantyFairy#1]
1. So, I've been standing on the first floor and reading that "folded piece of paper".

![Koikatu-2021-05-07-03-07-13-UI](https://user-images.githubusercontent.com/5585984/117380187-d5a27300-aee1-11eb-8941-ccf5f4841048.png)

---

2. One of the girls came to me and started talking.

![Koikatu-2021-05-07-03-09-04-UI](https://user-images.githubusercontent.com/5585984/117380190-d6d3a000-aee1-11eb-8bef-cd3d2d1069cb.png)

---

3. BOOM! Game over. You can't leave the dialogue sequence and stuck with the girl forever.

_Quite unfortunate, actually. I've been looking for some fresh non-H experience, even tried that awful kPlug thing, and then decided to try this plugin._

**Comment by ManlyMarco** [comment]
Fixed in https://github.com/IllusionMods/IllusionModdingAPI/releases/tag/v1.19

**Comment by Iniquitatis** [comment]
Thanks a lot! <3
