### ISSUE TITLE
Cannot exit quest dialog. 

### ISSUE THREAD

**Issue by AlpineWhite** [ManlyMarco/KK_PantyFairy#3]
Awesome mod, and lots of fun. It seemed like a DLC, so the quality way really good.

However, at the end of the quest I am encountering an error where I can close the completion m,essage but then the game hangs and the message come back up. Looking in the console logs it is showing:

[Error  : Unity Log] ArgumentException: GUILayout: Mismatched LayoutGroup.Repaint
Stack trace:
void UnityEngine.GUILayout.BeginHorizontal(GUILayoutOption[])
void RuntimeUnityEditor.Core.ObjectTree.ObjectTreeViewer.DisplayObjectTreeHelper(GameObject, int, int)
void RuntimeUnityEditor.Core.ObjectTree.ObjectTreeViewer.DisplayObjectTree()
void RuntimeUnityEditor.Core.ObjectTree.ObjectTreeViewer.WindowFunc(int)
void UnityEngine.GUI.CallWindowDelegate(WindowFunction, int, int, GUISkin, int, float, float, GUIStyle)

When the window first popped. Checking if this has been seen before.

**Comment by ManlyMarco** [comment]
This error is unrelated, send the entire output_log.txt file (after the crash happens).

**Comment by AlpineWhite** [comment]
I tried on three saves to replicate the issue and I am unable. THis seems to have been a certain set of actions which caused the issue. Subsequent attempts to recreate were not fruitful.
